### ISSUE TITLE
Add ability to extend final message with extra comment

### ISSUE THREAD

**Issue by mrerberg** [sawyerh/eslint-plugin-todo-plz#6]
Hi! Thanks for creating this plugin.

We use plugin and realised that final message with RegExp as example is not very obvious.

![Screenshot 2022-08-12 at 11 28 30](https://user-images.githubusercontent.com/103729911/184315911-d1d3cd03-a02b-4458-95b2-99e4e54d21bd.png)

I would like to suggest to add some extra setting that will allow to use custom comment as additional description. For example:

```text
TODO comment doesn't reference a ticket number. Comment pattern: TODO:\s\[http(s)?://jira.*\]
Example: TODO: [http://jira.net/browse/RTLF-650]
```

What do you think about this?

**Comment by sawyerh** [comment]
@mrerberg Thanks for the feedback, that's a great idea 👍🏻

**Comment by mrerberg** [comment]
Great! I will to try to open pull request soon then c:
